version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    # volumes:
    #   - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9094:9094"
    # volumes:
    #   - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
    
  central-station:
    image: central-station
    container_name: central-station
    environment:
    - KAFKA_TOPIC=weather
    - KAFKA_BROKER=kafka:9092
    - GROUP_ID=central-station

  weather-station-0:
    image: weather-station
    container_name: weather-station-0
    environment:
      - POLL_EVERY=1000
      - STATION_ID=0
      - STATION_LONGITUDE=47.1915
      - STATION_LATITUDE=-52.8371
      - KAFKA_TOPIC=weather
      - KAFKA_BROKER=kafka:9092
      - DROP_RATE=50
      - WEATHER_API=https://api.open-meteo.com/v1/forecast
    depends_on:
      - kafka

  weather-station-1:
      image: weather-station
      container_name: weather-station-1
      environment:
        - POLL_EVERY=1000
        - STATION_ID=1
        - STATION_LONGITUDE=28.1915
        - STATION_LATITUDE=-19.8371
        - KAFKA_TOPIC=weather
        - KAFKA_BROKER=kafka:9092
        - DROP_RATE=50
        - WEATHER_API=https://api.open-meteo.com/v1/forecast
      depends_on:
        - kafka

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local