apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: elastic-kibana
  name: elastic-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic-kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: elastic-kibana
    spec:
      containers:
        - env:
            - name: SSL_MODE
              value: "false"
          image: docker.io/nshou/elasticsearch-kibana:kibana7
          name: elastic-kibana
          ports:
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
status: {}
