apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: elastic-uploader
  name: elastic-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic-uploader
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: elastic-uploader
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOST
              value: elastic-kibana
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_UPLOADER_JAR
              value: /app/ElasticSearchUploader.jar
            - name: PARQUET_FILES_DIR
              value: /app/data/parquet
          image: elastic-uploader
          name: elastic-uploader
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: shared-volume
      restartPolicy: Always
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume
status: {}
