apiVersion: v1
kind: Service
metadata:
  labels:
    app: central-station-service
  name: central-station-service
spec:
  type: NodePort
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601

  selector:
    app: central-station
status:
  loadBalancer: {}
